.TH "PKGVIEW" "1" "May 26, 2020"
.SH "NAME"
pkgview \- a java based SVR4 package viewer
.SH "SYNOPSIS"
pkgview subcommand [arguments]
.SH DESCRIPTION
The pkgview utility allows the user to display properties of SVR4
packages installed on their system.
.LP
To see the available subcommands, invoke pkgview without any arguments.
