.TH "pkgview" "1" "Apr 24, 2013" "pkgview 1\&.3"
.SH "NAME"
pkgview \- a java based SVR4 package viewer
.SH "SYNOPSIS"
.LP
pkgview subcommand [arguments]
.SH DESCRIPTION
.LP
The pkgview utility allows the user to display prooperties of SVR4
packages installed on your system.
.LP
To see the available subcommands, invoke pkgview without any arguments.
