#!/bin/sh
#
# generate a prototype file for input to pkgmk
#
# feed to pkgmk like so:
#  pkgmk -d /tmp -f tt -r `pwd` TRIBpkgview
#

JARDIR=usr/share/pkgview
LIBDIR=usr/lib
OWNER="root bin"
SYSOWNER="root sys"

PKGTYPE="standalone"

echo "i pkginfo=./pkginfo"

echo "f none /usr/bin/pkgview=pkgview.installed 0755 ${OWNER}"
echo "d none /usr/share 0755 ${SYSOWNER}"
echo "d none /${JARDIR} 0755 ${OWNER}"
echo "d none /usr/share/man 0755 ${OWNER}"
echo "f none /usr/share/man/man1/pkgview.1=man1/pkgview.1 0644 ${OWNER}"
echo "f none /${JARDIR}/README=./README 0644 ${OWNER}"

for path in lib/java/*
do
	pname=`basename $path`
	echo "f none /${JARDIR}/${pname}=${path} 0644 ${OWNER}"
done
